# Generated by Django 3.2.7 on 2021-10-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_user_profile',
            name='aadhar',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee_user_profile',
            name='blood_grp',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='employee_user_profile',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee_user_profile',
            name='gender',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='employee_user_profile',
            name='pan',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee_user_profile',
            name='phone_no',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
    ]
