# Generated by Django 3.2.7 on 2021-10-05 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20211004_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_dept_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=50, null=True)),
                ('role', models.CharField(max_length=50, null=True)),
                ('salary', models.CharField(max_length=9, null=True)),
                ('leaves', models.PositiveSmallIntegerField(default=0)),
                ('dept_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dept_details', to='employee.employee')),
            ],
        ),
    ]
