# Generated by Django 3.2.7 on 2021-10-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_rename_username_profile_employee_user_profile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_no',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
