# Generated by Django 3.2.7 on 2021-10-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_bank_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_bank_details',
            old_name='bank_acc_no',
            new_name='bank_account_no',
        ),
        migrations.RenameField(
            model_name='employee_bank_details',
            old_name='per_address',
            new_name='permanent_address',
        ),
        migrations.RenameField(
            model_name='employee_bank_details',
            old_name='pf_no',
            new_name='pf_number',
        ),
        migrations.RenameField(
            model_name='employee_bank_details',
            old_name='temp_address',
            new_name='temporary_address',
        ),
        migrations.RenameField(
            model_name='employee_user_profile',
            old_name='blood_grp',
            new_name='blood_group',
        ),
        migrations.AlterField(
            model_name='employee_dept_details',
            name='salary',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
