# Generated by Django 3.2.7 on 2021-11-23 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20211006_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_bank_details',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='employee_bank_details',
            name='temporary_address',
        ),
        migrations.AddField(
            model_name='employee_user_profile',
            name='permanent_address',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee_user_profile',
            name='temporary_address',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Employee_salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_salary', models.CharField(max_length=12, null=True)),
                ('reimbursement_date', models.DateField(null=True)),
                ('transaction_id', models.CharField(max_length=30, null=True)),
                ('receipt_img', models.ImageField(null=True, upload_to='receipts')),
                ('salary_year', models.SmallIntegerField(default=2021)),
                ('salary_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_details', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaves_count', models.SmallIntegerField(default=20, null=True)),
                ('leaves_type', models.CharField(max_length=30, null=True)),
                ('leaves_from', models.DateTimeField()),
                ('leaves_to', models.DateTimeField()),
                ('leaves_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaves_details', to='employee.employee')),
            ],
        ),
    ]
