# Generated by Django 3.2.7 on 2021-11-25 11:43

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20211123_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_leaves',
            name='leaves_type',
        ),
        migrations.AddField(
            model_name='employee_leaves',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee_leaves',
            name='leaves_id',
            field=models.UUIDField(default=uuid.UUID('fac57b34-4de4-11ec-b85e-ac1203307617')),
        ),
        migrations.AddField(
            model_name='employee_leaves',
            name='leaves_reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='employee_leaves',
            name='total_leaves_count',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee_leaves',
            name='leaves_count',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='employee_leaves',
            name='leaves_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employee_leaves',
            name='leaves_to',
            field=models.DateField(null=True),
        ),
    ]
