# Generated by Django 3.2.7 on 2021-11-25 11:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20211125_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_leaves',
            name='leaves_id',
            field=models.UUIDField(default=uuid.UUID('4c5bea55-4de5-11ec-b423-ac1203307617')),
        ),
    ]
