# Generated by Django 3.2.7 on 2021-11-26 04:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_employee_leaves_leaves_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_leaves',
            name='leaves_id',
        ),
        migrations.AlterField(
            model_name='employee_leaves',
            name='leaves_from',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
