# Generated by Django 3.2.7 on 2021-11-26 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_auto_20211126_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_leaves',
            name='leaves_count',
            field=models.SmallIntegerField(default=32),
        ),
        migrations.AlterField(
            model_name='employee_leaves',
            name='leaves_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
