# Generated by Django 3.2.7 on 2021-11-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_auto_20211126_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_leaves',
            name='leaves_count',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employee_leaves',
            name='total_leaves_count',
            field=models.SmallIntegerField(default=32),
        ),
    ]
