# Generated by Django 3.2.3 on 2022-04-05 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_auto_20211130_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_leaves',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_leaves_details', to='employee.employee'),
        ),
    ]
